name: BoltOS Ubuntu Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm grub2 xorriso build-essential make grub-common mtools

    - name: Toolchain
      run: make toolchain

    - name: Build
      run: make

    - name: Upload bolt.iso
      uses: actions/upload-artifact@v3.0.0
      with:
        name: bolt.iso
        path: build/bolt.iso
        retention-days: 90
